### PR TITLE
Add a training module

### PR DESCRIPTION
**Pull request by th3uiguy**
@mountain01 could you squash-merge this to the domo-phoenix project?

### CODE REVIEW

**Comment by th3uiguy** [comment]
I am totally on board with making this it's own repo.

**Comment by mountain01** [comment]
I agree with @johnbwoodruff, this is super awesome but it should live in it's own repo.

**Comment by th3uiguy** [comment]
@mountain01 could you do that since I do not have access? I am happy to help if needed.

**Comment by mountain01** [comment]
Yep, I'm more than happy to do that!

**Comment by th3uiguy** [comment]
The project was created at https://github.com/DomoApps/StarterKit

**Pull request closed without merging**
